slices:
  - sources:
      - model: nlpguy/ColorShadow-7B
        layer_range: [0, 32]
      - model: Q-bert/Terminis-7B
        layer_range: [0, 32]
merge_method: slerp
base_model: nlpguy/ColorShadow-7B
parameters:
  t:
    - filter: self_attn
      value: [1, 0.5, 0.7, 0.3, 0]
    - filter: mlp
      value: [0, 0.5, 0.3, 0.7, 1]
    - value: 0.5 # fallback for rest of tensors
dtype: float16
